### ISSUE TITLE
Add property-based testing 're-entry speed' introduction

### ISSUE THREAD

**Issue by mankyKitty** [qfpl/state-machine-testing-course#16]
sigh, too tired...

We need to add some/more direction regarding the use/creation of generators. During the LJ workshop I was asked 'where to get the value of the `DrinkType`', whem creating the `cSetDrinkType` command generator.

This could simply be a matter of more notes and guidance around generators, but perhaps a `level00`  for a scorchingly fast introduction to property based testing?

**Comment by endgame** [comment]
A level00 warm-up, and links to the hedgehog docs in the top-level readme would go a long way.

**Comment by mankyKitty** [comment]
Okey dokey, I'll throw something together for this

**Comment by mankyKitty** [comment]
Fixed in #18
