### ISSUE TITLE
Level00 - Prism Laws

### ISSUE THREAD

**Issue by mankyKitty** [qfpl/state-machine-testing-course#19]
It's not obvious that the prism laws will fail to run because you haven't implemented either all of the laws or the combining property that runs them all. Needs more documentation, or rethink of layout.

The imports potentially form a cycle if participants try to complete the combined properties for all the prisms for the btree

**Comment by dtchepak** [comment]
To get these to run I added each property/lens combination individually. Also had to make `MyBTree` `deriving Eq`.

```haskell
...
  , testProperty "Prism First Prism Law MyBTree _Empty" (firstPrismLaw (Gen.constant ()) _Empty)
  , testProperty "Prism Second Prism Law MyBTree _Empty" (secondPrismLaw myBTreeGen _Empty)
  , testProperty "Prism Third Prism Law MyBTree _Empty" (thirdPrismLaw myBTreeGen _Empty)

  , testProperty "Prism First Prism Law MyBTree _Node" (firstPrismLaw (Gen.constant ()) _Empty)
  , testProperty "Prism Second Prism Law MyBTree _Node" (secondPrismLaw myNodeGen _Node)
  , testProperty "Prism Third Prism Law MyBTree _Node" (thirdPrismLaw myBTreeGen _Node)
  ]

  where myBTreeGen = genTree genMyBTreeVal
        myNodeGen :: Gen (MyBTree Int Char)
        myNodeGen = Node <$> genTree genMyBTreeVal <*> genMyBTreeVal <*>  genTree genMyBTreeVal
```

Aside: Second law property ended up like:

```haskell
-- preview l s ≡ Just a ==> review l a ≡ s
secondPrismLaw :: (Eq s, Show s) => Gen s -> Prism' s a -> Property
secondPrismLaw _gen _p = property $ do
    s <- forAll _gen
    maybe success (\a -> review _p a === s) (preview _p s)
```

I'm not sure if there is a way to do the implication: generate `s` such that `preview _p s === Just a` and give me that `a`. (I tried using `Gen.just` but couldn't link that output with a specific `s`)

**Comment by endgame** [comment]
Whether or not `deriving Eq` is the correct move is not clear. You could have two trees that are structurally different, but contain the same key/values. That might be a good `Eq` implementation, and checking that it's valid could be a good property test.

**Comment by mankyKitty** [comment]
We've dropped the prism exercises entirely and focused on building a lawful Eq instance. :tada:
