### ISSUE TITLE
ghcid command for running tests

### ISSUE THREAD

**Issue by dtchepak** [qfpl/state-machine-testing-course#20]
It would be great for the readme to show how to run `ghcid` to build and run tests. `ghcid -c 'cabal new-repl level00' --test=:main` does not work.

**Comment by mankyKitty** [comment]
Instructions for running the tests with `ghcid` has been merged, let me know if that works for you and you can close / add feedback here. :)

**Comment by dtchepak** [comment]
@mankyKitty Thanks, works for me! 👍 

Does `cabal new-repl` not support `.ghci` files? Does `ghci` pick up the dependencies installed by `cabal new-build`? (I have no idea how dependencies get resolved in `cabal new-repl` vs. `ghci`)
